# Generated by Django 3.2.8 on 2021-10-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=32, unique=True, verbose_name='город')),
                ('phone', models.PositiveIntegerField(default='+7(999)123 45 78', unique=True, verbose_name='телефон')),
                ('email', models.EmailField(blank=True, default='email@mail.ml', max_length=32, verbose_name='эл. почта')),
                ('adress', models.CharField(max_length=64, verbose_name='адресс')),
            ],
        ),
    ]
